services:
  scanbuddy-web:
    image: ghcr.io/harvard-nrg/scanbuddy:${SCANBUDDY_VERSION}
    restart: unless-stopped
    depends_on:
      - scanbuddy-broker
    environment:
      SCANBUDDY_PASS: ${SCANBUDDY_PASS}
      SCANBUDDY_SESSION_KEY: ${SCANBUDDY_SESSION_KEY}
    user: ${UID}:${GID}
    expose:
      - "8080"
    volumes:
      - ${INCOMING_DIR}:/data
      - ${CONFIG}:/etc/scanbuddy.yaml
    mem_limit: ${MEM_LIMIT}
    memswap_limit: ${MEM_SWAP_LIMIT}
    cpus: ${CPU_LIMIT}
    command: ["-c", "/etc/scanbuddy.yaml", "--folder", "/data", "--host", "0.0.0.0", "--broker-host", "scanbuddy-broker"]
    healthcheck:
      test: curl -sL -o /dev/null -u "${SCANBUDDY_USER}:${SCANBUDDY_PASS}" --fail localhost:8080
      interval: 30s
      timeout: 10s
      retries: 3

  scanbuddy-broker:
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    expose:
      - "6379"
    healthcheck:
      test: redis-cli ping

  scanbuddy-nginx:
    image: nginx:${NGINX_VERSION}
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "${BIND_ADDR}:${BIND_PORT}:80"
    expose:
      - "80"
    environment:
      no_proxy: "scanbuddy-web"
    depends_on:
      - scanbuddy-web
    healthcheck:
      test: curl -sL -o /dev/null -u "${SCANBUDDY_USER}:${SCANBUDDY_PASS}" --fail localhost
      interval: 30s
      timeout: 10s
      retries: 3

  scanbuddy-samba:
    image: ghcr.io/servercontainers/samba:${SAMBA_VERSION}
    restart: unless-stopped
    ports:
      - "445:445"
    expose:
      - "445"
    environment:
      SAMBA_CONF_LOG_LEVEL: 3
      WSDD2_DISABLE: 1
      AVAHI_DISABLE: 1
      NETBIOS_DISABLE: 1
      GROUP_fakegroup: 20
      ACCOUNT_scanbuddy: ${SAMBA_PASS}
      UID_scanbuddy: 501
      GROUPS_scanbuddy: fakegroup
      SAMBA_VOLUME_CONFIG_scanbuddy: "[scanbuddy]; path=/data; valid users = scanbuddy; guest ok = no; read only = no; browseable = yes"
    volumes:
      - ${INCOMING_DIR}:/data
    profiles: [samba]

